import os
print(os.getcwd())
print(os.listdir("C:\\Users\sayan\Desktop\coding चिज़े\codeforcers practice"))
os.chdir("C:\\Users\sayan\Desktop\coding चिज़े\codeforcers practice")
#print(os.getcwd())
#s.makedirs("Os module/fun")
os.chdir("C:\\Users\sayan\PycharmProjects\practice+learning")
#os.makedirs("Osname")
#os.rename("fuick off.py","fuckoff.py")
print(os.environ.get('Path'))
print(os.path.exists("C:\\Users\sayan\PycharmProjects\practice+learning"))