#write a python program to take 2 numbers and perform all the arithmatic operations
n1=int(input("Enter 1st no:"))
n2=int(input("Enter 2nd no:"))
print("Sum=",n1+n2)
print("substract",n1-n2)
print("multiply=",n1+n2)
print("divide=",n1/n2)
print("exponent=",n1**n2)
print("floor multiply=",n1//n2)
print("remainder=",n1%n2)
